# Generated by Django 2.1.2 on 2018-10-17 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, max_length=500, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('creditos', models.IntegerField(verbose_name='Créditos')),
                ('caragaHoraria', models.IntegerField(verbose_name='Carga Horária')),
                ('caragaHorariaObrigatoria', models.IntegerField(verbose_name='Carga Horária Obrigatória')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['departamento', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cargaHoraria', models.IntegerField(verbose_name='Carga Horária')),
                ('creditos', models.IntegerField(verbose_name='Créditos')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatoria', models.BooleanField(verbose_name='Obrigatória')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina do Curso',
                'verbose_name_plural': 'Disciplinas do Curso',
                'ordering': ['curso', 'disciplina'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('matricula', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('dataAdmissao', models.DateField(verbose_name='Data de Admissão')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Aluno', verbose_name='Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='MatriculaDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaFinal', models.IntegerField(verbose_name='Nota Final')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Disciplina', verbose_name='Disciplina')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Matrícula na disciplina',
                'verbose_name_plural': 'Matrículas nas disciplinas',
                'ordering': ['periodo', 'matricula'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('semestre', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-semestre'],
            },
        ),
        migrations.CreateModel(
            name='PreRequisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Disciplina', verbose_name='Disciplina')),
                ('preRequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PreRequisito', to='academico.Disciplina', verbose_name='Pré-Requisito')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('cfe', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CFE')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('complemento', models.CharField(blank=True, max_length=500, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de matrícula',
                'verbose_name_plural': 'Tipos de matrícula',
                'ordering': ['tipo'],
            },
        ),
        migrations.AddField(
            model_name='matriculadisciplina',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Periodo', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='tipoMatricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.TipoMatricula', verbose_name='Tipo de Matrícula'),
        ),
        migrations.AddField(
            model_name='curso',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Departamento', verbose_name='Departamento'),
        ),
    ]
