# Generated by Django 2.1.2 on 2018-10-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='caragaHoraria',
            new_name='cargaHoraria',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='caragaHorariaObrigatoria',
            new_name='cargaHorariaObrigatoria',
        ),
    ]
