# Generated by Django 2.1.2 on 2018-11-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_disciplina_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='notaFinal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Final'),
        ),
    ]
