# Generated by Django 2.1.2 on 2018-11-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20181119_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='finalMatricula',
            field=models.DateField(default='2018-06-01', verbose_name='Data final de matrícula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodo',
            name='inicioMatricula',
            field=models.DateField(default='2018-06-30', verbose_name='Inicio da data de matrícula'),
            preserve_default=False,
        ),
    ]
