# Generated by Django 2.1.2 on 2018-11-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_auto_20181120_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=255, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
                'ordering': ['situacao'],
            },
        ),
        migrations.AlterField(
            model_name='historico',
            name='notaFinal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Final'),
        ),
    ]
